import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st 

sns.set(style='dark')

df = pd.read_csv('dashboard/Clean_Data.csv')

df['timestamp'] = pd.to_datetime(df[['year', 'month', 'day', 'hour']])
df.set_index('timestamp', inplace=True)
df.interpolate(method='time', inplace=True)

def create_sum_Co2_byStation(data):
    station_CO2 = data.groupby('station')['CO'].sum().reset_index()
    return station_CO2

def create_sum_Emission_Yearly(data):
    Sum_Emission = data.groupby('year')[['PM2.5', 'PM10','SO2']].sum().reset_index()
    return Sum_Emission

def create_sum_emission(data):
    sum_emission = data[['PM2.5', 'PM10','SO2']].sum()
    return sum_emission
def create_last3Years(data):
    last_3Years = data[data['year'] >= 2015]
    Co_3Years = last_3Years.groupby('station')['CO'].sum().reset_index()
    return Co_3Years

sum_Co2 = create_sum_Co2_byStation(df)
sum_Emission_yearly = create_sum_Emission_Yearly(df)
sum_emission = create_sum_emission(df)
last_3Years = create_last3Years(df)


highest_value = sum_emission.max()

st.header('Data Analyst of Emission over 2013 - 2017')
st.subheader('Daily Emissions')

col1, col2 = st.columns(2)

with col1:
    worst_emission = sum_emission.idxmax()
    st.metric("Highest Emission Over 2013-2017", value= worst_emission)
with col2:
    highest_value = sum_emission.max()
    st.metric("Value of High Emission Over 2013-2017", value=highest_value)

col1, col2 = st.columns(2)
with col1:
    good_emission = sum_emission.idxmin()
    st.metric("Low Emission Over 2013-2017", value=good_emission)
with col2:
    low_value = sum_emission.min()
    st.metric('Value of Low Emission Over 2013-2017', value=low_value)
    

#air Pollution Level Over Time 
plt.figure(figsize=(12, 6))
plt.plot(df.index, df['PM2.5'], label='PM2.5', color='blue')
plt.plot(df.index, df['PM10'], label='PM10', color='green')
plt.plot(df.index, df['SO2'], label='SO2', color='red')
plt.xlabel('Timestamp')
plt.ylabel('Concentration')
plt.title('Air Pollution Levels Over Time')
plt.legend()
plt.grid(True)
plt.show()
st.pyplot(plt)

st.markdown("""
### Highest Emission:
- The pollutant with the highest emission over the period is **PM10**, with a total emission value of approximately **44,126,809**.
- PM10 represents particulate matter with a diameter of 10 micrometers or less, typically generated by dust, combustion, and industrial processes.

### Lowest Emission:
- The pollutant with the lowest emission is **SO2** (Sulfur Dioxide), with a total emission value of around **6,683,249**.
- SO2 is primarily produced by the burning of fossil fuels and can lead to acid rain, contributing to environmental and health hazards.
""")

# Yearly Total Concentrations of SO2,PM2.5, and PM10
plt.figure(figsize=(12, 8))
plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['PM2.5'], label='PM2.5', marker='o')
plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['PM10'], label='PM10', marker='o')
plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['SO2'], label='SO2', marker='o')
plt.title('Yearly Emission Concentrations of SO2, PM2.5 and PM10 (2013-2017)')
plt.xlabel('Year')
plt.ylabel('Concentration (µg/m³)')
plt.legend()
plt.grid(True)


# Menampilkan plot di Streamlit
st.title('Yearly Total Concentrations of SO2, PM2.5, and PM10')
st.pyplot(plt)

col1,col2,col3 = st.columns(3)
with col1:
    plt.figure(figsize=(12,8))
    plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['PM2.5'], color ='blue', label='PM2.5', marker='o')
    plt.title('Emission Of PM2.5 (2013-2017)',fontsize = 35)
    plt.xlabel('year',fontsize = 30)
    plt.ylabel('Concentration (µg/m³)',fontsize = 30)
    plt.grid(True)
    st.pyplot(plt)
with col2:
    plt.figure(figsize=(12,8))
    plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['PM10'], color ='orange', label='PM10', marker='o')
    plt.title('Emission Of PM10 (2013-2017)',fontsize = 35)
    plt.xlabel('year',fontsize = 30)
    plt.ylabel('Concentration (µg/m³)',fontsize = 30)
    plt.grid(True)
    st.pyplot(plt)
with col3:
    plt.figure(figsize=(12,8))
    plt.plot(sum_Emission_yearly['year'], sum_Emission_yearly['SO2'], color ='green', label='SO2', marker='o')
    plt.title('Emission Of SO2 (2013-2017)',fontsize = 35)
    plt.xlabel('year',fontsize = 30)
    plt.ylabel('Concentration (µg/m³)',fontsize = 30)
    plt.grid(True)
    st.pyplot(plt)

st.subheader("Conclusions")
st.markdown("""
### Based on the graph:
1. **PM10** had the highest emission levels throughout the observed years, peaking around 2014, followed by a significant decline after 2016.
2. **PM2.5** showed a gradual decline after 2014, maintaining relatively stable levels compared to PM10.
3. **SO2** emissions were consistently lower, with only slight fluctuations, and experienced a small downward trend between 2014 and 2017.

### Key Observations:
- Both **PM2.5** and **PM10** showed an increase until 2014, followed by a downward trend.
- **SO2** concentrations remained low and steady, with a slight decline over time.
- The most dramatic reduction in emissions was observed for **PM10** between 2016 and 2017, indicating a possible implementation of stricter air quality controls or other mitigation measures.
""")

    
fig, ax = plt.subplots(figsize=(20, 10))
colors = ["#90CAF9", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3","#D3D3D3","#D3D3D3","#D3D3D3","#D3D3D3","#D3D3D3","#D3D3D3","#D3D3D3"]

# Plot barplot
sns.barplot(
    y='station',
    x='CO',
    data= sum_Co2.sort_values(by='CO', ascending=False),
    palette=colors,
    ax=ax
)

# Set title and labels
ax.set_title("Total CO Emissions by Stations (2013-2017)", loc="center", fontsize=30)
ax.set_ylabel(None)
ax.set_xlabel(None)
ax.tick_params(axis='y', labelsize=20)
ax.tick_params(axis='x', labelsize=15)
st.pyplot(fig)

plt.figure(figsize=(12, 6))
plt.bar(last_3Years['station'], last_3Years['CO'], color='skyblue')
plt.title('Total CO Emissions by Station (2015-2017)',fontsize = 25)
plt.xlabel('Station')
plt.ylabel('Total CO Emissions')
plt.xticks(rotation=90)
plt.grid(True)
plt.show()
st.pyplot(plt)

st.markdown("""
            ### Based on the graph:
            Station of Wanshou Xigong was the highest station with poor air quality from 2013 -2017 
            and Dingling station was the lowest with poor air quality 
            """)

plt.figure(figsize=(10, 8))
sns.heatmap(df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Between Pollutants')
plt.show()
st.pyplot(plt)


plt.figure(figsize=(10, 8))
plt.scatter(df['PM2.5'], df['PM10'], alpha=0.5)
plt.xlabel('PM2.5')
plt.ylabel('PM10')
plt.title('PM2.5 vs PM10')
plt.grid(True)
plt.show()
st.pyplot(plt)
